version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/esp-idf-qemu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/speki-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/tanks-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/vhdl_rpn-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/tdd-platform"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/android-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/zephyr-dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/zephyr-fuzz"
    schedule:
      interval: "weekly"
    directory: "/quartus-prime"
    schedule:
      interval: "weekly"
    directory: "/quartus-prime-aji"
    schedule:
      interval: "weekly"
    directory: "/neorv32_soc"
    schedule:
      interval: "weekly"
  