version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/esp-idf-qemu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/speki-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/tanks-ci"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/tdd-platform"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/aji_openocd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dev-base"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/questasim"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/quartus"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/riscv-gcc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/spinalhdl-with-ghdlyosys"
    schedule:
      interval: "weekly"
  