# Source: https://github.com/actions/container-action/issues/2

name: example

on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikleberg/quartus-prime:latest
      options: --mac-address=00:ab:ab:ab:ab:ab

    steps:
    - uses: actions/checkout@v3

    - name: Run Simulation
      run: vsim -c -do <script>.tcl

    - name: Run Synthesis
      run: quartus_sh -t <script>.tcl
