# Sources: 
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1144
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2344

default:
  image: ghcr.io/nikleberg/quartus-prime:latest

stages:
  - build

# This only works if the docker runner has CAP_NET enabled.
example:
  stage: build
  before_script: |
    apt-get -q -y update
    apt-get -q -y install net-tools
    ifconfig eth0 down
    ifconfig eth0 hw ether "00:ab:ab:ab:ab:ab"
    ifconfig eth0 up
  script: |
    vsim -c -do <script>.tcl
    quartus_sh -t <script>.tcl
