# See: https://github.com/Azure/container-scan#ignoring-vulnerabilities
general:
  vulnerabilities:
    - CVE-2022-0492 # speki-ci, no fix as of 12.02.2022
    - CVE-2022-23222 # speki-ci, no fix as of 12.02.2022
    - CVE-2019-1010083 # esp-idf-qemu, gdbgui of idf requires specified version
  bestPracticeViolations:
    - CIS-DI-0001
    - DKL-DI-0006
    - CIS-DI-0005
    - CIS-DI-0006
    - CIS-DI-0008
