name: CI/CD

on: [push, pull_request]

jobs:
  dockerhub:
    name: Build images for DockerHub
    uses: NikLeberg/container_builder/.github/workflows/container_builder.yml@main
    with:
      registry: docker.io
      username: nikolodion
      images: >-
        ["esp-idf-qemu"]
      push: ${{github.event_name == 'push'}}
    secrets:
      password: ${{secrets.DOCKERHUB_PASSWORD}}

  github:
    name: Build images for GitHub registry
    uses: NikLeberg/container_builder/.github/workflows/container_builder.yml@main
    with:
      registry: ghcr.io
      username: ${{github.actor}}
      images: >-
        ["speki-ci", "tanks-ci", "vhdl_rpn-ci"]
      push: ${{github.event_name == 'push'}}
    secrets:
      password: ${{secrets.GITHUB_TOKEN}}
