name: CI/CD

on: [push, pull_request]

jobs:
  dockerhub:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [esp-idf-qemu]
    uses: NikLeberg/container_builder/.github/workflows/container_builder.yml@main
    with:
      registry: docker.io
      username: nikolodion
      image: ${{matrix.image}}
      push: ${{github.event_name == 'push'}}
    secrets:
      password: ${{secrets.DOCKERHUB_PASSWORD}}

  github:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [speki-ci, tanks-ci, vhdl_rpn-ci]
    uses: NikLeberg/container_builder/.github/workflows/container_builder.yml@main
    with:
      registry: ghcr.io
      username: ${{github.actor}}
      image: ${{matrix.image}}
      push: ${{github.event_name == 'push'}}
    secrets:
      password: ${{secrets.GITHUB_TOKEN}}
