name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Names of container images for their respective registries. (Space separated)
  dockerhub: "esp-idf-qemu"
  github: "speki-ci tanks-ci vhdl_rpn-ci tdd-platform"

jobs:

  detect_changes:
    name: Detect Changes
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    outputs:
      dockerhub-changed: ${{steps.changed-containers.outputs.dockerhub-changed}}
      github-changed: ${{steps.changed-containers.outputs.github-changed}}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed Containers
        id: changed-containers
        run: .github/workflows/detect_changes.sh "${{env.dockerhub}}" "${{env.github}}"

  dockerhub:
    name: DockerHub
    needs: detect_changes
    if: needs.detect_changes.outputs.dockerhub-changed != ''
    uses: ./.github/workflows/container_builder.yml
    with:
      registry: docker.io
      username: nikolodion
      images: ${{needs.detect_changes.outputs.dockerhub-changed}}
      push: ${{github.ref_name == 'main'}}
    secrets:
      password: ${{secrets.DOCKERHUB_PASSWORD}}

  github:
    name: GitHub registry
    needs: detect_changes
    if: needs.detect_changes.outputs.github-changed != ''
    uses: ./.github/workflows/container_builder.yml
    with:
      registry: ghcr.io
      username: nikleberg
      images: ${{needs.detect_changes.outputs.github-changed}}
      push: ${{github.ref_name == 'main'}}
    secrets:
      password: ${{secrets.GITHUB_TOKEN}}
