name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Names of container images for their respective registries. (Space separated)
  dockerhub: "esp-idf-qemu android-ci"
  github: "speki-ci tanks-ci vhdl_rpn-ci tdd-platform"

jobs:

  detect_changes:
    name: Detect Changes
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    outputs:
      dockerhub-changed: ${{steps.changed-containers.outputs.dockerhub-changed}}
      github-changed: ${{steps.changed-containers.outputs.github-changed}}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed Containers
        id: changed-containers
        run: .github/workflows/detect_changes.sh "${{env.dockerhub}}" "${{env.github}}"

  dockerhub:
    name: DockerHub
    needs: detect_changes
    if: needs.detect_changes.outputs.dockerhub-changed != ''
    uses: ./.github/workflows/container_builder.yml
    with:
      registry: docker.io
      username: nikolodion
      images: ${{needs.detect_changes.outputs.dockerhub-changed}}
      push: ${{github.ref_name == 'main'}}
    secrets:
      password: ${{secrets.DOCKERHUB_PASSWORD}}

  github:
    name: GitHub registry
    needs: detect_changes
    if: needs.detect_changes.outputs.github-changed != ''
    uses: ./.github/workflows/container_builder.yml
    with:
      registry: ghcr.io
      username: nikleberg
      images: ${{needs.detect_changes.outputs.github-changed}}
      push: ${{github.ref_name == 'main'}}
    secrets:
      password: ${{secrets.GITHUB_TOKEN}}

  summarize:
    # Allows to enforce branch protection rules by requiring that this job
    # and expecially all its 'needs' succeeded.
    # See: https://github.com/actions/runner/issues/491
    name: Summarize
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    needs: [dockerhub, github]
    if: always()
    steps:
      - name: Successful builds?
        run: |
          if ${{ contains(needs.*.result, 'failure') }}; then
            echo "One or more matrix builds have failed!"
            false
          fi
          if ${{ contains(needs.*.result, 'cancelled') }}; then
            echo "One or more matrix builds were cancelled!"
            false
          fi
