name: container_builder

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      images:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: ${{fromJson(inputs.images)}}
    defaults:
      run:
        shell: bash
        working-directory: ./${{matrix.image}}
    env:
      image_tag: ${{inputs.registry}}/${{inputs.username}}/${{matrix.image}}:latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to Registry
        run: echo ${{secrets.password}} | docker login ${{inputs.registry}} -u ${{inputs.username}} --password-stdin
        
      - name: Run pre_build Script
        run: |
          if [ -e ./pre_build.sh ]
          then
            ./pre_build.sh
          fi
        
      - name: Build Container
        run: docker build --pull -t ${{env.image_tag}} .

      - name: Scan Container
        uses: azure/container-scan@v0.1
        with:
          image-name: ${{env.image_tag}}
          username: ${{inputs.username}}
          password: ${{secrets.password}}
        
      - name: Run post_build Script
        run: |
          if [ -e ./post_build.sh ]
          then
            ./post_build.sh
          fi
        
      - name: Push Container
        if: ${{inputs.push}}
        run: docker push ${{env.image_tag}}
