name: container_builder

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      images:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: ${{fromJson(inputs.images)}}
    defaults:
      run:
        shell: bash
        working-directory: ./${{matrix.image}}
    env:
      image_tag: ${{inputs.registry}}/${{inputs.username}}/${{matrix.image}}:latest
    steps:

      - name: Maximize Build Space
        working-directory: .
        run: |
          echo "Available storage (pre cleanup):"
          df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/swift
          echo "Available storage (after cleanup):"
          df -h

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run pre_build Script
        id: pre_build
        run: |
          if [ -e ./pre_build.sh ]
          then
            ./pre_build.sh
          fi
        
      - name: Build Container
        run: docker build --pull -t ${{env.image_tag}} .

      - name: Scan Container with Trivy
        if: steps.pre_build.outputs.trivy_skip != 'skip'
        uses: aquasecurity/trivy-action@master
        with:
          security-checks: vuln
          image-ref: ${{env.image_tag}}
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          timeout: 20m0s

      - name: Scan Container with Dockle
        if: steps.pre_build.outputs.dockle_skip != 'skip'
        uses: erzz/dockle-action@v1.3.1
        with:
          image: ${{env.image_tag}}
          failure-threshold: FATAL
          exit-code: 1
          timeout: 20m
          dockle-version: "0.4.5"

      - name: Upload Scan Results
        if: steps.pre_build.outputs.trivy_skip != 'skip'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: .
        
      - name: Run post_build Script
        run: |
          if [ -e ./post_build.sh ]
          then
            ./post_build.sh
          fi
        
      - name: Push Container
        if: inputs.push
        run: |
          echo ${{secrets.password}} | docker login ${{inputs.registry}} -u ${{inputs.username}} --password-stdin
          docker push ${{env.image_tag}}
          docker logout ${{inputs.registry}}
