name: container_builder

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      images:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: ${{fromJson(inputs.images)}}
    defaults:
      run:
        shell: bash
        working-directory: ./${{matrix.image}}
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to Registry
        run: docker login -u ${{inputs.username}} -p ${{secrets.password}} ${{inputs.registry}}
        
      - name: Run pre_build Script
        run: |
          if [ -e ./pre_build.sh ]
          then
            ./pre_build.sh
          fi
        
      - name: Build Image
        run: docker build --pull -t ${{inputs.username}}/${{matrix.image}}:latest .
        
      - name: Push Image
        if: ${{inputs.push}}
        run: docker push ${{inputs.username}}/${{matrix.image}}:latest
        
      - name: Run post_build Script
        run: |
          if [ -e ./post_build.sh ]
          then
            ./post_build.sh
          fi
