name: container_builder

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      image:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{inputs.username}}
          password: ${{secrets.password}}
          
      - name: Run pre_build Script
        if: hashFiles('${{inputs.image}}/pre_build.sh') != ''
        shell: bash
        run: ${{inputs.image}}/pre_build.sh
        
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: ${{inputs.image}}/Dockerfile
          push: ${{github.event_name == 'push'}}
          tags: ${{inputs.username}}/${{inputs.image}}:latest

      - name: Run post_build Script
        if: hashFiles('${{inputs.image}}/post_build.sh') != ''
        shell: bash
        run: ${{inputs.image}}/post_build.sh
